[pytest]
minversion = 6.0

# Add the package's source and test directories to the Python path
pythonpath = src tests

# Test discovery settings
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*

# Pytest command-line options
addopts = 
    --import-mode=importlib
    --rich
    --show-capture=no
    -vv
    -s

# Show more detailed test output
verbose = 2
